git-svn-id: https://k9copy.svn.sourceforge.net/svnroot/k9copy/trunk@60 250c61c0-cc0d-0410-af45-d4f8fccfe43b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1900,7 +1900,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=k9copy
- VERSION=1.0.4
+ VERSION=1.0.5
 
 
 cat >>confdefs.h <<_ACEOF
@@ -31282,6 +31282,279 @@ fi
 
 
 
+# HAL check from kdebase/kioslave/media
+
+
+# Check whether --with-hal or --without-hal was given.
+if test "${with_hal+set}" = set; then
+  withval="$with_hal"
+  ac_cv_use_hal=$withval
+else
+  ac_cv_use_hal=yes
+
+fi;
+
+if test "x$ac_cv_use_hal" = "xyes" ; then
+
+########### Check for the HAL
+
+  echo "$as_me:$LINENO: checking for the HAL" >&5
+echo $ECHO_N "checking for the HAL... $ECHO_C" >&6
+
+  hal_inc=NOTFOUND
+  hal_lib=NOTFOUND
+  hal=NOTFOUND
+
+  search_incs="$kde_includes /usr/include /usr/include/hal /usr/local/include /usr/local/include/hal"
+
+hal_incdir=NO
+for i in $search_incs;
+do
+  for j in libhal.h libhal-storage.h;
+  do
+    echo "configure: 31315: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      hal_incdir=$i
+      break 2
+    fi
+  done
+done
+
+
+  if test -r $hal_incdir/libhal.h ; then
+    HAL_INCS="-I$hal_incdir"
+    hal_inc=FOUND
+  fi
+
+  if test -r $hal_incdir/libhal-storage.h ; then
+    hal_storage_version=4
+    grep LibHalVolume $hal_incdir/libhal-storage.h \
+    > /dev/null 2>&1 && hal_storage_version=5
+    if test $hal_storage_version = 4 ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAL_0_4
+_ACEOF
+
+    fi
+  fi
+
+  search_libs="$kde_libraries /usr/lib64 /usr/lib /usr/local/lib"
+
+hal_libdir=NO
+for i in $search_libs;
+do
+  for j in libhal.so;
+  do
+    echo "configure: 31350: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      hal_libdir=$i
+      break 2
+    fi
+  done
+done
+
+
+  if test -r $hal_libdir/libhal.so ; then
+    HAL_LIBS="-L$hal_libdir -lhal"
+    hal_lib=FOUND
+  fi
+
+
+  if test $hal_inc = FOUND && test $hal_lib = FOUND ; then
+      echo "$as_me:$LINENO: result: headers $hal_incdir  libraries $hal_libdir" >&5
+echo "${ECHO_T}headers $hal_incdir  libraries $hal_libdir" >&6
+  	hal=FOUND
+  else
+      echo "$as_me:$LINENO: result: searched but not found" >&5
+echo "${ECHO_T}searched but not found" >&6
+  fi
+
+
+
+
+
+########### Check for DBus
+
+  echo "$as_me:$LINENO: checking for DBus" >&5
+echo $ECHO_N "checking for DBus... $ECHO_C" >&6
+
+  dbus_inc=NOTFOUND
+  dbus_lib=NOTFOUND
+  dbus=NOTFOUND
+
+  search_incs="$kde_includes /usr/include /usr/include/dbus-1.0 /usr/local/include /usr/local/include/dbus-1.0"
+
+dbus_incdir=NO
+for i in $search_incs;
+do
+  for j in dbus/dbus.h;
+  do
+    echo "configure: 31395: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      dbus_incdir=$i
+      break 2
+    fi
+  done
+done
+
+
+  search_incs_arch_deps="$kde_includes /usr/lib64/dbus-1.0/include /usr/lib/dbus-1.0/include /usr/local/lib/dbus-1.0/include"
+
+dbus_incdir_arch_deps=NO
+for i in $search_incs_arch_deps;
+do
+  for j in dbus/dbus-arch-deps.h;
+  do
+    echo "configure: 31412: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      dbus_incdir_arch_deps=$i
+      break 2
+    fi
+  done
+done
+
+
+  if test -r $dbus_incdir/dbus/dbus.h && test -r $dbus_incdir_arch_deps/dbus/dbus-arch-deps.h ; then
+    DBUS_INCS="-I$dbus_incdir -I$dbus_incdir_arch_deps"
+    dbus_inc=FOUND
+  fi
+
+  search_libs="$kde_libraries /usr/lib64 /usr/lib /usr/local/lib"
+
+dbus_libdir=NO
+for i in $search_libs;
+do
+  for j in libdbus-1.so;
+  do
+    echo "configure: 31434: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      dbus_libdir=$i
+      break 2
+    fi
+  done
+done
+
+
+  if test -r $dbus_libdir/libdbus-1.so ; then
+    DBUS_LIBS="-L$dbus_libdir -ldbus-1"
+    dbus_lib=FOUND
+  fi
+
+  if test $dbus_inc = FOUND && test $dbus_lib = FOUND ; then
+    echo "$as_me:$LINENO: result: headers $dbus_incdir $dbus_incdir_arch_deps  libraries $dbus_libdir" >&5
+echo "${ECHO_T}headers $dbus_incdir $dbus_incdir_arch_deps  libraries $dbus_libdir" >&6
+    dbus=FOUND
+  else
+    echo "$as_me:$LINENO: result: searched but not found" >&5
+echo "${ECHO_T}searched but not found" >&6
+  fi
+
+
+
+
+########### Check for DBus-Qt bindings
+
+  echo "$as_me:$LINENO: checking for DBus-Qt bindings" >&5
+echo $ECHO_N "checking for DBus-Qt bindings... $ECHO_C" >&6
+
+  dbusqt_inc=NOTFOUND
+  dbusqt_lib=NOTFOUND
+  dbusqt=NOTFOUND
+
+  search_incs="$kde_includes /usr/include /usr/lib64/dbus-1.0/include /usr/include/dbus-1.0 /usr/local/include /usr/local/include/dbus-1.0"
+
+dbusqt_incdir=NO
+for i in $search_incs;
+do
+  for j in dbus/connection.h;
+  do
+    echo "configure: 31477: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      dbusqt_incdir=$i
+      break 2
+    fi
+  done
+done
+
+
+  if test -r $dbusqt_incdir/dbus/connection.h ; then
+    have_qt_patch=0
+    grep dbus_connection_setup_with_qt_main $dbusqt_incdir/dbus/connection.h \
+    > /dev/null 2>&1 && have_qt_patch=1
+    if test $have_qt_patch = 1 ; then
+      DBUSQT_INCS="-I$dbusqt_incdir"
+      dbusqt_inc=FOUND
+    fi
+  fi
+
+  search_libs="$kde_libraries /usr/lib /usr/lib64 /usr/local/lib"
+
+dbusqt_libdir=NO
+for i in $search_libs;
+do
+  for j in libdbus-qt-1.so;
+  do
+    echo "configure: 31504: $i/$j" >&5
+    if test -r "$i/$j"; then
+      echo "taking that" >&5
+      dbusqt_libdir=$i
+      break 2
+    fi
+  done
+done
+
+
+  if test -r $dbusqt_libdir/libdbus-qt-1.so ; then
+    DBUSQT_LIBS="-L$dbusqt_libdir -ldbus-qt-1"
+    dbusqt_lib=FOUND
+  fi
+
+  if test $dbusqt_inc = FOUND && test $dbusqt_lib = FOUND ; then
+    echo "$as_me:$LINENO: result: headers $dbusqt_incdir libraries $dbusqt_libdir" >&5
+echo "${ECHO_T}headers $dbusqt_incdir libraries $dbusqt_libdir" >&6
+    dbusqt=FOUND
+  else
+    echo "$as_me:$LINENO: result: searched but not found" >&5
+echo "${ECHO_T}searched but not found" >&6
+  fi
+
+
+
+fi
+
+########### Check if media HAL backend sould be compiled
+
+have_hal=no
+HAL_DBUS_LIBS=""
+if test "x$hal" = "xFOUND" && test "x$dbus" = "xFOUND" && test "x$dbusqt" = "xFOUND" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_HAL
+_ACEOF
+
+  have_hal=yes
+  HAL_DBUS_LIBS="$HAL_LIBS $DBUS_LIBS $DBUSQT_LIBS"
+fi
+
+
+
+if test x$have_hal = xyes; then
+  include_HAL_TRUE=
+  include_HAL_FALSE='#'
+else
+  include_HAL_TRUE='#'
+  include_HAL_FALSE=
+fi
+
+
+
 
 
 DO_NOT_COMPILE="$DO_NOT_COMPILE CVS debian bsd-port admin"
@@ -31336,7 +31609,11 @@ done
 
           ac_config_files="$ac_config_files k9vamps/Makefile"
 
+          ac_config_files="$ac_config_files libdvdnav/Makefile"
+
           ac_config_files="$ac_config_files libk3bdevice/Makefile"
+
+          ac_config_files="$ac_config_files libk3bdevice.new/Makefile"
 
           ac_config_files="$ac_config_files libk9copy/Makefile"
 
@@ -31469,6 +31746,13 @@ if test -z "${ARCH_X86_64_TRUE}" && test -z "${ARCH_X86_64_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ARCH_X86_64\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ARCH_X86_64\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${include_HAL_TRUE}" && test -z "${include_HAL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"include_HAL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"include_HAL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -31927,7 +32211,9 @@ do
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "k9decmpeg/Makefile" ) CONFIG_FILES="$CONFIG_FILES k9decmpeg/Makefile" ;;
   "k9vamps/Makefile" ) CONFIG_FILES="$CONFIG_FILES k9vamps/Makefile" ;;
+  "libdvdnav/Makefile" ) CONFIG_FILES="$CONFIG_FILES libdvdnav/Makefile" ;;
   "libk3bdevice/Makefile" ) CONFIG_FILES="$CONFIG_FILES libk3bdevice/Makefile" ;;
+  "libk3bdevice.new/Makefile" ) CONFIG_FILES="$CONFIG_FILES libk3bdevice.new/Makefile" ;;
   "libk9copy/Makefile" ) CONFIG_FILES="$CONFIG_FILES libk9copy/Makefile" ;;
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
